# Generated by Django 5.0.2 on 2024-04-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_marca_alter_user_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cor", models.CharField(max_length=45)),
            ],
        ),
    ]
