# Generated by Django 5.0.2 on 2024-04-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_cor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Modelo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome_modelo", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
